controller_joint_names: ['', 'front_right_axel_joint', 'front_right_wheel_joint', 'front_left_axel_joint', 'front_left_wheel_joint', 'back_left_axel_joint', 'back_left_wheel_joint', 'back_right_axel_joint', 'back_right_wheel_joint', ]
