controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    use_sim_time: true

    # joint_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
        type: velocity_controllers/JointGroupVelocityController

# joint_trajectory_controller:
#   ros__parameters:
#     joints:
#       - back_right_wheel_joint
#       - back_left_wheel_joint
#       - front_right_wheel_joint
#       - front_left_wheel_joint
#     interface_name: velocity
#     command_interfaces:
#       - velocity
#       - position
#     state_interfaces:
#       - position
#       - velocity

velocity_controller:
  ros__parameters:
    joints:
      - back_right_wheel_joint
      - back_left_wheel_joint
      - front_right_wheel_joint
      - front_left_wheel_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
