controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    use_sim_time: true

    joint_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_velocity_controller:
        type: velocity_controllers/JointGroupVelocityController

    # forward_position_controller:
    #   type: forward_command_controller/ForwardCommandController

# forward_position_controller:
#   ros__parameters:
#     joints:
#       - back_right_axel_joint
#       - back_left_axel_joint
#       - front_right_axel_joint
#       - front_left_axel_joint
#     interface_name: position

joint_position_controller:
  ros__parameters:
    joints:
      - back_right_axel_joint
      - back_left_axel_joint
      - front_right_axel_joint
      - front_left_axel_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity


joint_velocity_controller:
  ros__parameters:
    joints:
      - back_right_wheel_joint
      - back_left_wheel_joint
      - front_right_wheel_joint
      - front_left_wheel_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
