##############################################################################
#
# GitGub CI workflow syntax spec:
#    https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# Coveralls example:
#    https://github.com/marketplace/actions/coveralls-github-action
#
##############################################################################

name: Build

on:
  # Triggered whenever push to the master branch
  push:
    branches:
      - main
      - iteration_1
      - iteration_2

  # Triggered whenever a pull request is created on master
  pull_request:
    branches: ["main"]
    types: [opened]

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    # Create a container of the latest Ubuntu, other values could be
    # ubuntu-latest, ubuntu-22.04, etc.
    runs-on: ubuntu-20.04

    steps:
      
      # Install some system pacakges
      - name: Install ROS 2 Galactic packages
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install -y curl
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-galactic-ros-base python3-colcon-common-extensions


      - name: Setup Workspace
        run: |
          source /opt/ros/galactic/setup.bash
          mkdir -p ros_ws/src/project_legion
          cd ros_ws
          colcon build
          source install/setup.bash

      # We want to use GitHub CI checkout version 3 for checking out the branch
      - uses: actions/checkout@v3
        with:
          path: ros_ws/src/project_legion

      # Build for test coverage
      - name: Configure CMake flags and build exectables
        run: |
          source /opt/ros/galactic/setup.bash
          sudo apt install python3-rosdep
          sudo rosdep init
          rosdep update --include-eol-distros
          cd ros_ws
          rosdep install --from-paths src -y --ignore-src
          colcon build --packages-select project_legion

    

      # Run CMake to setup compilation flags
      # - name: Configure Coverage CMake
      #   run: cmake -D COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug -B ${{github.workspace}}/build

      # Compile and executables
      # - name: Build Coverage
      #   working-directory: ${{github.workspace}}
      #   run: make

      # Run test suite and compute code coverage
      # - name: Run Test Coverage
      #   working-directory: ${{github.workspace}}
      #   run: make code_coverage

      # Upload coverage result to Coverage.io
      # - name: Upload result to Coveralls.io
      #   uses: coverallsapp/github-action@1.1.3
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: ${{github.workspace}}/build/coverage.info.cleaned