# This is a basic workflow to help you get started with Actions

name: project_legion_build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Install ROS Galactic
        run: |
          locale  # check for UTF-8

          sudo apt update && sudo apt install locales
          sudo locale-gen en_US en_US.UTF-8
          sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
          export LANG=en_US.UTF-8
          
          locale  # verify settings
      
      - name: Setup Resources
        run: |
          sudo apt install software-properties-common
          sudo add-apt-repository universe

      - name: Add ROS2 GPG Key
        run: |
          sudo apt update && sudo apt install curl
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

      - name: Add Repository to source list
        run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null



      # Runs a set of commands using the runners shell
      - name: Install ROS2 Packages
        run: |
          sudo apt update
          sudo apt upgrade
      
      - name: Install ROS2 Galactic
        run: sudo apt install ros-galactic-ros-base

      - name: Workspace Setup
        run: |
          source /opt/ros/galactic/setup.bash
          mkdir -p ~/ros_ws/src
          cd ros_ws
          colcon build
          source install/setup.bash


      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
         path: ros_ws/src/project_legion
        
      - name: Build Package
        run: |
          source /opt/ros/galactic/setup.bash
          cd ros_ws
          rosdep install -i --from-path src --rosdistro galactic -y
          colcon build